#Configurando rotas da aplicação para o gateway
spring:
    application:
        name: hr-api-gateway
    cloud:
        gateway:
            #Aqui estamos definindo um timeout geral das rotas
            #Mas também é possível definir individualmente por rota
            httpclient:
                connect-timeout: 10000
                response-timeout: 5s
            routes:
                - id: payments-route
                  #"lb://" indica que o Spring Cloud Gateway deve
                  # rotear a solicitação para o serviço por meio
                  # do balanceador de carga interno.
                  uri: lb://hr-payroll
                  predicates:
                    - Path=/payments/**

                - id: workers-route
                  uri: lb://hr-worker
                  predicates:
                    - Path=/workers/**
                    
                - id: worker-actuator-route
                  uri: lb://hr-worker
                  predicates:
                    - Path=/actuator/**
                    
                - id: users-route
                  uri: lb://hr-user
                  predicates:
                    - Path=/users/**
                - id: oauth-route
                  uri: lb://hr-oauth
                  predicates:
                    - Path=/hr-oauth/**
                    
                    
#Porta default para a aplicação
server:
    port: 8765

eureka:
    client:
        fetchRegistry: true
        registerWithEureka: true
        service-url:
            defaultZone: http://localhost:8761/eureka
        
