spring:
    application:
        name: hr-oauth


server:
    port: ${PORT:0}
    servlet:
        context-path: /${spring.application.name}

eureka:
    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
        fetchRegistry: true
        registerWithEureka: true
        service-url:
            defaultZone: http://localhost:8761/eureka
